repos:
  - repo: local
    hooks:
      - id: pre-commit-checks
        name: Pre-commit checks (lint)
        entry: make pre-commit-hook
        language: system
        pass_filenames: false
        always_run: true
